version: 2
jobs:
  build:
    working_directory: ~/copa-app
    docker:
      - image: circleci/node:10.18
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: lint
          command: yarn run lint
      - run:
          name: build
          command: yarn run build
      - run:
          name: release
          command: yarn run semantic-release || true
